### ISSUE TITLE
libsmdev_usb.c:74:16: error: expected expression before ‘struct’ USBDEVFS_IOCTL

### ISSUE THREAD

**Issue by blshkv** [libyal/libewf#85] opened 2017-08-01 08:00 UTC
```
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common    -march=native -O2 -pipe -Wall -c -o libsmdev_track_value.lo libsmdev_track_value.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -march=native -O2 -pipe -Wall -c libsmdev_track_value.c  -fPIC -DPIC -o .libs/libsmdev_track_value.o
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -march=native -O2 -pipe -Wall -c libsmdev_track_value.c -o libsmdev_track_value.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common    -march=native -O2 -pipe -Wall -c -o libsmdev_usb.lo libsmdev_usb.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -march=native -O2 -pipe -Wall -c libsmdev_usb.c  -fPIC -DPIC -o .libs/libsmdev_usb.o
In file included from libsmdev_usb.c:32:0:
libsmdev_usb.c: In function ‘libsmdev_usb_ioctl’:
libsmdev_usb.c:74:16: error: expected expression before ‘struct’
                USBDEVFS_IOCTL,
                ^
libsmdev_usb.c: In function ‘libsmdev_usb_control_command’:
libsmdev_usb.c:149:16: error: expected expression before ‘struct’
                USBDEVFS_CONTROL,
                ^
libsmdev_usb.c: In function ‘libsmdev_usb_test’:
libsmdev_usb.c:197:16: error: expected expression before ‘struct’
                USBDEVFS_CONNECTINFO,
                ^
make[1]: *** [Makefile:773: libsmdev_usb.lo] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-forensics/libewf-20170703/work/libewf-20170703/libsmdev'
make: *** [Makefile:850: all-recursive] Error 1
 * ERROR: app-forensics/libewf-20170703::pentoo failed (compile phase):
 *   emake failed

```

**Comment by blshkv** [comment] 2017-08-01 08:03
https://gist.github.com/blshkv/f6c78c7809cb7b9fb090b309702575c0

**Comment by blshkv** [comment] 2017-08-01 08:11
sys-kernel/linux-headers-4.4 (/usr/include/linux/usbdevice_fs.h)
kernel.osrelease = 4.8.17

Do let me know if you need any additional info.

**Comment by blshkv** [comment] 2017-08-01 08:16
That seems like a https://github.com/libyal/libsmdev issue..

**Comment by blshkv** [comment] 2017-08-01 08:24
sorry for the spam.

The package compiles fine with local ```libcfile```.  Perhaps, ```libcfile-20170105``` has a newer structure.

**Comment by blshkv** [comment] 2017-08-02 01:26
the workaround is to install libsmdev (it was a "local") as a system library too.

**Comment by joachimmetz** [comment] 2019-01-08 20:39
I've been unable to reproduce this. CI tests now include "local" and "shared" library build. Closing this issue, reopen if issue still persists

**Closed by joachimmetz** 2019-01-08 20:39 UTC
