### ISSUE TITLE
ewfverify: memory exhaustion

### ISSUE THREAD

**Issue by mmgu** [libyal/libewf#8] opened 2014-11-05 07:42 UTC
Create encase-7 ex01 files for a 512GB dm-zero device:

    echo '0 1000000000 zero' | dmsetup create z1
    ewfacquire -C test -u -q -d sha1 -m fixed -f encase7-v2 -c fast -S 200000000 -t test /dev/mapper/z1
    
This created 7 files, test.Ex01...Ex07, each has a size of nearly 500MB.
Run ewfverify against these files:

    ewfverify test.Ex01

The memory usage of ewfverify process grows linearly over time and become nearly 2GB at about 90% of the verification process, causing the whole system to hang up.
This was tested on a 64-bit Ubuntu 14.04.1 system with 2GB RAM.

**Comment by danzek** [comment] 2015-03-24 16:02
Has this been resolved? I also encountered this error.

**Comment by joachimmetz** [comment] 2015-03-24 18:12
> I also encountered this error using the latest version available from macports two weeks ago.
I don't have a crystal ball, what version are you talking about?

> Has this been resolved?
Since the issue is still open what do you think?

**Comment by hydrocloricacid** [comment] 2015-04-20 05:14
I have had this issue also. From packages   ewf-tools 20140608(GRML14.11 x64) and libewf 20140608-1 from libyal which was built yesterday.

Solution for me was to use the ewf-tools (version=20100226-1+b1) package from debian stable.

My computer has 8GB RAM. 
1.9TB of E01 evidence files which is an acquisition of a 2TB HDD
It will die at about 74%.

Happy to help by testing any changes against this evidence.

**Comment by joachimmetz** [comment] 2016-03-25 20:43
This appears to be a combination of issues in the experimental version.
Closing this issue and tracking progress in https://github.com/libyal/libewf/issues/38.

**Closed by joachimmetz** 2016-03-25 20:43 UTC
Labels: bug
