### ISSUE TITLE
./config shows NO fuse support

### ISSUE THREAD

**Issue by siftuser** [libyal/libewf#115] opened 2018-11-13 17:30 UTC
osxfuse (3.8.2) is installed. 

Installing **libewf** using 'setup.py'

but `./config` continues to show 

```
checking for fuse... no
checking fuse.h usability... no
checking fuse.h presence... no
checking for fuse.h... no
checking fuse.h usability... no
checking fuse.h presence... no
checking for fuse.h... no
```

Any help would be greatly appreciated! Thanks!

**Comment by joachimmetz** [comment] 2018-11-13 19:52
is there still a "fuse compatibility" option in the osxfuse installation? You'll need to install that.

**Comment by siftuser** [comment] 2018-11-14 04:50
Thanks for the clue ... I verified that the option for "MacFUSE compatibility layer" was enabled during installation. Restarted the system. but no change in `./configure` output .. I am sure missing something. Thanks for advice :)

**Comment by joachimmetz** [comment] 2018-11-14 04:56
Check config.log that should contain more detail if configure can find the fuse header files.

**Comment by siftuser** [comment] 2018-11-14 08:11
Thanks @joachimmetz !

This is what I see in the config.log file .. any help ? Thanks much in advance!

```
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
```
Couldn't find fuse.pc on manual search ... 

```
/usr/local/include/fuse/fuse_common.h:32:2: error: Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
#error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!
 ^
/usr/local/include/fuse/fuse_common.h:271:8: error: On Darwin API version 25 or greater must be used
#            error On Darwin API version 25 or greater must be used
             ^
2 errors generated.
```

**Comment by joachimmetz** [comment] 2018-11-14 11:10
fuse.pc is the pkg_config "package configuration", mainly used by Linux to my knowledge.

The other 2 issues the m4 script should detect (see below). Could you attach or mail the config.log so I can have a look.

`#error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!`

https://github.com/libyal/libewf/blob/master/m4/libfuse.m4#L87

`#            error On Darwin API version 25 or greater must be used`

https://github.com/libyal/libewf/blob/master/m4/libfuse.m4#L84

**Comment by siftuser** [comment] 2018-11-15 03:57
@joachimmetz verified I have the same M4 scripts :) emailed config.log file. Thank you :)

**Comment by joachimmetz** [comment] 2018-11-15 06:57
So your config.log says:
```
Building:
   ...
   GUID/UUID support:                        native
   FUSE support:                             libosxfuse
```

**Comment by joachimmetz** [comment] 2018-11-15 06:59
`checking for fuse.h... no` this is normal since the fuse header file of osxfuse is `osxfuse/fuse.h` not `fuse.h`. Closing issue working as intended.

**Closed by joachimmetz** 2018-11-15 06:59 UTC
Labels: question

**Comment by joachimmetz** [comment] 2018-11-15 07:01
Also setup.py will **only** build the Python-binding only. If you want ewfmount use `./configure`.
Also see: https://github.com/libyal/libewf/wiki/Building

**Comment by siftuser** [comment] 2018-11-15 14:53
Thanks you so much for your time & invaluable support @joachimmetz
