### ISSUE TITLE
OSError: pyewf_handle_write_buffer: unable to write data

### ISSUE THREAD

**Issue by sspring** [libyal/libewf#107] opened 2018-08-24 02:41 UTC
1. Can I put sha256 or sha512 value to ewf file? I find the libewf_handle_set_sha1_hash and libewf_handle_set_md5_hash only.
2. What ewf format support sha256/sha512?

**Comment by joachimmetz** [comment] 2018-08-24 05:49
"defacto" EWF does not support sha256/sha512. The [ewf-x](https://github.com/libyal/libewf/blob/master/documentation/Expert%20Witness%20Compression%20Format%20(EWF).asciidoc#4-ewf-x) (libewf custom additions) does. However other tools might not understand these extensions.

**Comment by sspring** [comment] 2018-08-24 06:51
What function I can use to put sha256 to ewf file if I want to use ewf-x? maybe libewf_handle_set_utf8_hash_value?

**Comment by joachimmetz** [comment] 2018-08-24 06:53
Yes, (from memory) that should be the right function. You can also check the ewfacquire source.

**Comment by sspring** [comment] 2018-08-24 07:40
The  web server recieves data from http post stream and writes it to a file in ewf format. I'm thinking about libewf can continue to write from the previous position if any error occurred(like network error).I find a flag LIBEWF_OPEN_WRITE_RESUME for libewf_handle_open  defined in definitions.h. What's the next?(seek operation need?)

**Comment by joachimmetz** [comment] 2018-08-24 09:00
Libewf is not built with network streams in mind (let alone the EWF format). Ewfacquirestream allows you store streamed data in EWF files. Write resume is designed to resume copying a local device e.g. after a power issue. It assumes you are able to read the original media and recalculate the hashes.

**Comment by sspring** [comment] 2018-08-24 09:14
Yes. I'm going to handle network stream without libewf.also I want to call lib function directly instead of using ewfacquire. Don't worry about hashes,I will serialize hash state on error occurred and restore it if necessary. So How can I continue the work with unfinished ewf file?

**Comment by joachimmetz** [comment] 2018-08-24 09:43
There is no append mode. Resume here is technically not suspend-resume, but more continue-where-previously-failed.

From: https://github.com/libyal/libewf/blob/master/ewftools/imaging_handle.c#L604

* open in write resume,
* re-initialize hashes
* find location in source that was last reliably stored in EWF (https://github.com/libyal/libewf/blob/master/ewftools/imaging_handle.c#L941)
* continue writing to EWF
* close the EWF

> Don't worry about hashes,I will serialize hash state on error occurred and restore it if necessary. 

The gotcha here is that you serialized hash state needs to match that of the location in source that was last reliably stored in EWF. The keyword here is reliably seeing the write resume will "back-track" on data that was not reliably stored.

**Comment by sspring** [comment] 2018-08-24 10:01
I really appreciate your help.

**Comment by sspring** [comment] 2018-08-24 10:52
Have you tested write-resume on pyewf?  
I create an ewf file as below:
```
In [45]: f = pyewf.open(["F:\\3"],"w")

In [46]: f.get_chunk_size()
Out[46]: 32768

In [47]: f.write_buffer(b"0"*32768)

In [48]: f.close()
```
Then,I try to reopen and write it:
```
In [49]: f2 = pyewf.open(["F:\\3.E01"],"a")
In [50]: f2.get_offset()
Out[50]: 32768
In [52]: f2.write_buffer(b"1"*32768)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-52-affd77fee5ee> in <module>()
----> 1 f2.write_buffer(b"1"*32768)

OSError: pyewf_handle_write_buffer: unable to write data.
```
What happened?

**Comment by sspring** [comment] 2018-08-24 10:54
pyewf version:20171104  
OS: Windows 10 64bit 1803 17134
python version: 3.6.6 |Anaconda 64bit

**Comment by joachimmetz** [comment] 2018-08-24 11:29
The 20171104 version of libewf (including pyewf) is considered experimental. I know all things are not properly working yet. Please use https://github.com/libyal/libewf-legacy instead

**Comment by sspring** [comment] 2018-08-25 04:57
I'm very sorry I have to bother you again. I have the same problem using pyewf 20140804.  
```
In [1]: import pyewf

In [2]: f = pyewf.open(["F:\\1"],"w")

In [3]: f.write_buffer(b"1"*32768)

In [4]: f.close()  
# ---- F:\1.e01 has generated successfully since here ----
In [5]: f = pyewf.open(["F:\\1.E01"],"a")

In [6]: f.get_offset()
Out[6]: 32768

In [7]: f.write_buffer(b"0"*32768)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-6a47cafdb780> in <module>()
----> 1 f.write_buffer(b"0"*32768)

OSError: pyewf_handle_write_buffer: unable to write data.

In [8]: pyewf.get_version()
Out[8]: '20140804'
```

**Comment by joachimmetz** [comment] 2018-08-25 08:48
I'll have a look when time permits.

**Comment by joachimmetz** [comment] 2020-11-28 19:44
So this is working as intended. As I said before resume here is technically not suspend-resume, but more continue-at-safe-point-where-previously-failed.

```
f.media_size
32768
```

You  cannot add more data since all the data has been written. Closing issue

**Closed by joachimmetz** 2020-11-28 19:44 UTC
Labels: needs a closer look, question
