### ISSUE TITLE
Customized ewfacquire unable to read from Windows device with "incorrect parameter"

### ISSUE THREAD

**Issue by samicheema** [libyal/libewf#137] opened 2020-01-31 05:53 UTC
Hi, 

I am facing another issue that failed to acquire logical drive C:\ , all other logical drives are working fine in case of logical drives acquisitions. Please guide me. Thanks

**Comment by joachimmetz** [comment] 2020-01-31 07:14
Which version of libewf, libsmdev and libcfile are you using?

**Comment by samicheema** [comment] 2020-01-31 07:15
@joachimmetz, I don't know the version as it was used by my application.

**Comment by joachimmetz** [comment] 2020-01-31 07:29
> I don't know the version as it was already used by my application.

what is your application? 

under the libewf source there is libsmdev/ and libcfile/ subdirectories in each of those directories there is a lib*_definition.h file that file contains a version number

**Comment by samicheema** [comment] 2020-01-31 07:36
Thanks @joachimmetz, I found that its "20110104".

**Comment by joachimmetz** [comment] 2020-01-31 07:40
> I found that its "20110104".

Which is the version of what? libewf, libsmdev or libcfile?

Can you provide me the versions of libewf, libsmdev and libcfile. And please add the name of the library with the version.

Also what is this application you are talking about

**Comment by samicheema** [comment] 2020-01-31 07:48
Please find the detail:

libewf - "20110104"
libsmdev - "20110104"
I have libcstring instead of libcfile and its version is "2010-20111219"

Its an application of mine to take images of the drive.

**Comment by joachimmetz** [comment] 2020-01-31 07:56
That sounds like a very old version of libewf. Please update to the latest libewf (stable) https://github.com/libyal/libewf-legacy/releases/tag/20140808 and see if the issue persists.

**Comment by samicheema** [comment] 2020-01-31 08:02
@joachimmetz, please guide me if I can copy some thing from your provided source. Because on building my libewf project dll files are created. Please see the screenshot

![image](https://user-images.githubusercontent.com/26224408/73522199-9b6a3c00-4429-11ea-8f5b-bd0762635b50.png)

**Comment by joachimmetz** [comment] 2020-01-31 08:14
I'm not sure what you are asking me. You can find instructions on how to build a libewf.dll here https://github.com/libyal/libewf/wiki/Building. Reading the device though is done by ewfacquire (libsmdev, libcfile) and not by libewf itself.

**Comment by samicheema** [comment] 2020-02-04 08:09
@joachimmetz , I am trying to build you provided latest libewf (https://github.com/libyal/libewf-legacy/releases/tag/20140808). But no success. Please see few errors below:
![Screenshot_2](https://user-images.githubusercontent.com/26224408/73725603-8eae5680-474f-11ea-9b94-e312dcb9dbbc.png)

**Comment by joachimmetz** [comment] 2020-02-04 08:13
Please read the build instructions carefully you'll need to run the sync
libs and autogen scripts first. Also see the appveyor configuration.

**Comment by samicheema** [comment] 2020-02-11 12:36
Hi @joachimmetz, Thanks for the help, I was able to build successfully. Now I have updated "ewfacquire.c" with following changes:
* Added following lines
........
int interactive_mode                                            = 1;
	int result                                                      = 0;

	/*************/
	int argc = 38;
	wchar_t *argv[64];
	*(argv)		= _SYSTEM_STRING( "samiacquire" );
	*(argv+1)	= _SYSTEM_STRING( "-b" );
	*(argv+2)	= _SYSTEM_STRING( "64" );
	*(argv+3)	= _SYSTEM_STRING( "-B" );
	*(argv+4)	= _SYSTEM_STRING( "104857600" );//cpSizeToAcquireForDemoMode;
	*(argv+5)	= _SYSTEM_STRING( "-c" );
	*(argv+6)	= _SYSTEM_STRING( "empty-block" );//cpComp;
	*(argv+7)	= _SYSTEM_STRING( "-C" );
	*(argv+8)	= _SYSTEM_STRING( "1" );
	*(argv+9)	= _SYSTEM_STRING( "-d" );
	*(argv+10)	= _SYSTEM_STRING( "sha1" );
	*(argv+11)	= _SYSTEM_STRING( "-D" );//
	*(argv+12)	= _SYSTEM_STRING( "description" );
	*(argv+13)	= _SYSTEM_STRING( "-E" );
	*(argv+14)	= _SYSTEM_STRING( "1" );
	*(argv+15)	= _SYSTEM_STRING( "-e" );
	*(argv+16)	= _SYSTEM_STRING( "sami" );
	*(argv+17)	= _SYSTEM_STRING( "-g" );
	*(argv+18)	= _SYSTEM_STRING( "64" );
	*(argv+19)	= _SYSTEM_STRING( "-N" );
	*(argv+20)	= _SYSTEM_STRING( "notes" );
	*(argv+21)	= _SYSTEM_STRING( "-f" );
	*(argv+22)	= _SYSTEM_STRING( "ftk" );//cpEwfFormat;
	*(argv+23)	= _SYSTEM_STRING( "-m" );
	*(argv+24)	= _SYSTEM_STRING( "fixed" );
	*(argv+25)	= _SYSTEM_STRING( "-M" );
	*(argv+26)	= _SYSTEM_STRING( "physical" );	
	*(argv+27)	= _SYSTEM_STRING( "-o" );
	*(argv+28)	= _SYSTEM_STRING( "0" );
	*(argv+29)	= _SYSTEM_STRING( "-S" );
	*(argv+30)	= _SYSTEM_STRING( "1.9GiB" );
	*(argv+31)	= _SYSTEM_STRING( "-P" );
	*(argv+32)	= _SYSTEM_STRING( "512" );
	*(argv+33)	= _SYSTEM_STRING( "-r" );
	*(argv+34)	= _SYSTEM_STRING( "2" );
	*(argv+35)	= _SYSTEM_STRING( "-t" );
	*(argv+36)	= _SYSTEM_STRING( "D:\\ewfCreated" );//cpDest;
	*(argv+37)	= _SYSTEM_STRING( "\\\\.\\G:" );//cpSource;
	/*************/

	libcnotify_stream_set( stderr, NULL );
......
*Build and execute _awfacquire.exe_ from Release directory. But getting the screenshot errors. Could you please guide what possible reasons of it. Thanks
![Capture](https://user-images.githubusercontent.com/26224408/74237135-9f813e00-4cf4-11ea-96df-b84912f70d7a.PNG)

**Comment by joachimmetz** [comment] 2020-02-11 13:00
This is libsmdev/libcfile telling you the call to the WINAPI call GetFileAttributesW failed with error "incorrect parameter"

https://github.com/libyal/libcfile/blob/master/libcfile/libcfile_support.c#L383

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesw

**Comment by samicheema** [comment] 2020-02-11 13:05
@joachimmetz, please suggest how it can be fixed. Because I am executing the _awfacquire.exe_ . Is there any code fix?

**Comment by joachimmetz** [comment] 2020-02-11 14:09
Since this is a WINAPI function it is hard for me to assess why it is failing without the system itself. You need to determine first why this call is failing on your system.

**Comment by samicheema** [comment] 2020-02-11 14:13
@joachimmetz, I was not facing this issue in my older [version](https://github.com/libyal/libewf/issues/137#issuecomment-580623550). Getting when executed the [latest ](https://github.com/libyal/libewf-legacy/releases/tag/20140808)one.

**Comment by joachimmetz** [comment] 2020-02-11 14:19
This does not provides me with the necessary information. I've indicated to you multiple times now that I need to know the versions of libsmdev and libcfile. It could be that GetFileAttributesW was not called in the version you have used previously. However we would still need to figure out why this is failing with an undocumented error code.

**Comment by samicheema** [comment] 2020-02-11 14:26
@joachimmetz, Please find the version details:

libsmdev : LIBSMDEV_VERSION				20110104

Please note that _libcfile_ was never used in my older version.

**Comment by joachimmetz** [comment] 2020-02-11 14:39
Please be more descriptive / explaining, otherwise I have to ask a lot of follow up questions to help debug the issue.

> LIBSMDEV_VERSION 20110104

* I assume this the old version you were using?
* If so what are the new versions you are using? Of both libsmdev and libcfile?
* Can you tell me more about the type of device you are read from?

**Comment by samicheema** [comment] 2020-02-11 14:51
@joachimmetz, 
> I assume this the old version you were using?
Yes, this was the older version I was using before your recommendation.

> If so what are the new versions you are using? Of both libsmdev and libcfile?
I am using your recommended [release ](https://github.com/libyal/libewf-legacy/releases/tag/20140808) and its version are as follow
libsmdev : LIBSMDEV_VERSION				20191221
libcfile  : LIBCFILE_VERSION				20200126

I was trying to read but failed in both. 
1: A physical drive ( \\.\PhysicalDrive1 ) 
2: Logical drive ( \\.\G: ) with file system NTFS

Please see the below screenshot for further reference. 
![image](https://user-images.githubusercontent.com/26224408/74247419-d280fd00-4d07-11ea-9be1-2293d8c4f2f0.png)

**Comment by joachimmetz** [comment] 2020-02-11 15:23
Which windows version? Is this running within a VM (if so which virtualization product)?

I'll see if I can try to reproduce it, when time permits.

**Comment by samicheema** [comment] 2020-02-11 15:29
@joachimmetz, I am using on Windows 7 (Professional version). No, its not on any VM but if you want to access it, I can make some arrangements for you. Thanks for your support and time, I really appreciate that.
Please also see the screenshot for detail:
![image](https://user-images.githubusercontent.com/26224408/74250978-41ad2000-4d0d-11ea-8b42-45443308e649.png)

**Comment by joachimmetz** [comment] 2020-02-12 20:28
From empirical debugging it looks like GetFileAttributesW does not work on Windows device paths. I'll change libcfile exists functions to support some of the more common Windows device file paths.

**Comment by joachimmetz** [comment] 2020-02-12 20:33
Closing this issue in favor of https://github.com/libyal/libcfile/issues/5

**Closed by joachimmetz** 2020-02-12 20:33 UTC
Labels: enhancement

**Comment by joachimmetz** [comment] 2020-02-12 20:38
A hacky work around for the time being is to comment out the call to GetFileAttributesW in libcfile_support.c in libcfile_exists_wide.

**Comment by samicheema** [comment] 2020-02-13 10:38
@joachimmetz, thank you for your support and prompt responses. This issue has been fixed at my end by the hacky work around suggested by you. 

Thanks again (y).
