### ISSUE TITLE
test failures due to missing files

### ISSUE THREAD

**Issue by themaddoctor** [libyal/libewf#94] opened 2018-01-29 04:59 UTC

**Comment by themaddoctor** [comment] 2018-01-29 04:59
===========================================
   libewf 20171104: tests/test-suite.log
===========================================

# TOTAL: 12
# PASS:  1
# SKIP:  3
# XFAIL: 0
# FAIL:  8
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_glob.sh
==================

Missing test executable: ./ewf-20171104_test_glob.exe
FAIL test_glob.sh (exit status: 1)

FAIL: test_write_functions.sh
=============================

Missing test executable: ./ewf-20171104_test_write.exe
FAIL test_write_functions.sh (exit status: 1)

SKIP: test_ewfinfo.sh
=====================

Test input directory: input not found.
SKIP test_ewfinfo.sh (exit status: 77)

SKIP: test_ewfexport.sh
=======================

Test input directory: input not found.
SKIP test_ewfexport.sh (exit status: 77)

FAIL: test_ewfexport_logical.sh
===============================

Missing test executable: ../ewf-20171104tools/ewf-20171104export.exe
FAIL test_ewfexport_logical.sh (exit status: 1)

SKIP: test_ewfverify.sh
=======================

Test input directory: input not found.
SKIP test_ewfverify.sh (exit status: 77)

FAIL: test_ewfverify_logical.sh
===============================

Missing test executable: ../ewf-20171104tools/ewf-20171104verify.exe
FAIL test_ewfverify_logical.sh (exit status: 1)

FAIL: test_ewfacquire.sh
========================

Missing test executable: ../ewf-20171104tools/ewf-20171104acquire.exe
FAIL test_ewfacquire.sh (exit status: 1)

FAIL: test_ewfacquire_optical.sh
================================

Missing test executable: ../ewf-20171104tools/ewf-20171104acquire.exe
FAIL test_ewfacquire_optical.sh (exit status: 1)
building on linux
```
FAIL: test_ewfacquirestream.sh
==============================

Missing test executable: ../ewf-20171104tools/ewf-20171104acquirestream.exe
FAIL test_ewfacquirestream.sh (exit status: 1)

FAIL: test_ewfacquire_resume.sh
===============================

Missing executable: ../ewf-20171104tools/ewf-20171104acquire.exe
FAIL test_ewfacquire_resume.sh (exit status: 1)

```

**Comment by joachimmetz** [comment] 2018-01-29 06:17
This is work in progresss. Marking as duplicate of https://github.com/libyal/libewf/issues/37

**Closed by joachimmetz** 2018-01-29 06:17 UTC
Labels: question
