### ISSUE TITLE
windows msys

### ISSUE THREAD

**Issue by serius777** [libyal/libewf#45] opened 2016-05-19 12:52 UTC
hi, i got error when building libewf (experimental 20160424) with msys in mingw. i have zlib, bzip2 and Crypto API librra. i follow this article #https://github.com/libyal/libewf/wiki/Building#using-msys-mingw, but fail while make.

> Making all in include
> make[1]: Entering directory `/home/HUDA/libewf-20160424/include'
> make[1]: Nothing to be done for `all'.
> make[1]: Leaving directory `/home/HUDA/libewf-20160424/include'
> Making all in common
> make[1]: Entering directory `/home/HUDA/libewf-20160424/common'
> make  all-am
> make[2]: Entering directory `/home/HUDA/libewf-20160424/common'
> make[2]: Leaving directory `/home/HUDA/libewf-20160424/common'
> make[1]: Leaving directory `/home/HUDA/libewf-20160424/common'
> Making all in libcstring
> make[1]: Entering directory `/home/HUDA/libewf-20160424/libcstring'
> /bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall   -o libcstring.la  libcstring_support.lo libcstring_wide_string.lo  -lbz2 -lz 
> libtool: link: rm -fr  .libs/libcstring.lax
> libtool: link: lib -OUT:.libs/libcstring.lib .libs/libcstring_support.o .libs/libcstring_wide_string.o 
> make[1]: Leaving directory `/home/HUDA/libewf-20160424/libcstring'

and error messages
../libtool: line 1095: lib: command not found
make[1]: *** [libcstring.la] Error 127
make: *** [all-recursive] Error 1

i google 
> lib: command not found

but no one work. any one know this issue?
my OS is win7 64-bit, and i am not sure if i install mingw 64 bit (there is mingw32 folder inside mingw directory). i don't have any problem while build libewf (same version) in centos. please helpme.

**Comment by joachimmetz** [comment] 2016-05-21 05:37
Looks like an issue with your build environment, check if libtool is properly installed.

**Comment by serius777** [comment] 2016-05-21 14:57
hi joachimmetz, thank you for your reply.
i installed libtool with mingw-get.exe. i am new in mingw (of course C/C++ compilation to), i am used IDE like netbeans (cygwin and mingw) and microsoft visual studio for code and compiling. i read that make output and i think lthat ibtool want to create libcstring.lib, libcstring_support.o, and libcstring_wide_string.o with lib command and i guess that is lib.exe. So i run lib in msys console and the output is

> sh: lib: command not found

i googled that lib command, but i only got it's implementation. i want to know what is lib command? where is it? why i or libtool cannot run it? how to install it? how can i or libtool run it?

**Comment by joachimmetz** [comment] 2016-05-21 15:13
The error does not provide much useful detail, what I assume could be the issue is that something is missing or broken. Which can be hard to troubleshoot remotely. If you're familiar with Visual Studio why don't you use the Visual Studio build files instead?

**Comment by serius777** [comment] 2016-05-21 16:01
hi joachimmets, thank you for reply my question.
is lib command provided with mingw? unfortunely i am not advance in C/C++ even with Visual Studio (code C/C++ just for excercise). realy i don't know if we can distribute our code C/C++ programs or librarys and let people compile it with their compiler (i think we can only get excercise code and executable program. i think only PHP and other interpreter language code can distributed), oh my thought is so tiny (i am realy sory). With Visual Studio  while compiling, i got error with dokan (in centos i not use dokan). And i use mingw, because i want to learn C++ with QT, and then i need this library to create forensic program.

sould i reinstall mingw?

**Comment by joachimmetz** [comment] 2016-05-21 16:11
> is lib command provided with mingw?

it is more likely a broken error message

> With Visual Studio while compiling, i got error with dokan (in centos i not use dokan). 

If you're not using ewfmount, just ignore dokan not building.

> realy i don't know if we can distribute our code C/C++ programs or librarys and let people compile it with their compiler 

I'm missing context here, I have no idea what you are trying to tell me. There are far more issues with distributing binaries than source. I opt to learn more about that first. For QT also read: https://www.qt.io/qt-licensing-terms/

> And i use mingw, because i want to learn C++ with QT

Why not start with C++ and QT on Linux?

**Comment by serius777** [comment] 2016-05-22 12:14
hi joachimmetz, thank you for your reply.
i try to compile libewf use VS 2012 with dokan. there is no problem with dokan. but there is an error while compiling. I got error **C1060: compiler is out of heap space** in libcthreads_thread_pool.c (libcthreads) line 44.
I try to increase compiler heap size with including option **/Zm2000**, but the error stil appear. and i try to compile it with 64-bit compiler and got same error. I try to compile only libcthread to and i got same error again. is it compiler problem? do you know about this issue?

**Comment by joachimmetz** [comment] 2016-05-22 12:23
> do you know about this issue?

I'm not familiar with this issue. [MSDN](https://msdn.microsoft.com/en-us/library/yz7kx3y2.aspx) has some pointers though.

**Comment by serius777** [comment] 2016-05-25 14:35
hi joachimmetz.
Thank you for your advice. Now i can compile libewf with mingw (from [mingw.org](http://www.mingw.org/)), I just reinstall my MinGW installation and follow MinGW and msys installation, also libewf compilation from https://github.com/libyal/libewf/wiki/Building#using-msys-mingw. May be i did some miss configuration before.
Thank you very much.

**Comment by joachimmetz** [comment] 2016-05-26 03:48
Good to hear, closing issue.

**Closed by joachimmetz** 2016-05-26 03:48 UTC
Labels: question
