### ISSUE TITLE
ewfverify fails on large drives on 32 bit systems

### ISSUE THREAD

**Issue by theraven82** [libyal/libewf#18] opened 2015-03-18 09:04 UTC
Ewfverify fails on large images. I've used ewfverify on the images of a large (3TB) disk, and ewfverify consistently fails at the same point. The error messages suggest there is a problem with reading the evidence files, but the images are verified correctly in EnCase. 

I've tried outputting more verbose error logs, but the resulting log file stays empty. I've used the latest version (libewf-20140608.tar.gz), and built it in Ubuntu 12.04 x86, and the latest Mint (17.1) x86. 

I've used the same version of libewf to verify the evidence files on a 64 bit system, and the verification passes. 

Is it perhaps a limitation of 32 bit systems, or is there a possible bug?

The error messages from the console:

```
Status: at 38%.
        verified 1.0 TiB (1163113988096 bytes) of total 2.7 TiB (3000592982016 bytes).
        completion in 2 hour(s), 56 minute(s) and 32 second(s) with 167 MiB/s (175637613 bytes/second).

Status: at 38%.
        verified 1.0 TiB (1163994595328 bytes) of total 2.7 TiB (3000592982016 bytes).
        completion in 2 hour(s), 56 minute(s) and 38 second(s) with 167 MiB/s (175534864 bytes/second).

Status: at 38%.
        verified 1.0 TiB (1164875137024 bytes) of total 2.7 TiB (3000592982016 bytes).
        completion in 2 hour(s), 56 minute(s) and 45 second(s) with 167 MiB/s (175421980 bytes/second).

Verify failed at: Mar 13, 2015 13:25:09
Unable to verify input.
libewf_handle_read_buffer: unable to read chunk data: 35570143.
verification_handle_read_buffer: unable to read storage media buffer.
verification_handle_verify_input: unable to read data.
ewfverify: FAILURE

**Comment by gregfreemyer** [comment] 2015-03-18 17:48
I have had a similar issue, except with 2TB images.  I do get different error messages than you.

I assume both my issue and yours are another manifestation of issue #8 (Memory Exhaustion).  

With libewf-20140608, memory consumption appears to grow linearly with image size.  About 0.5% of the image size per my testing if I recall correctly, so a 2TB image takes about 10 GB of memory (ram + virtual) to verify.  A 32-bit version of libewf can't address that much memory (real or virtual).

I'm just a user, but it is on my to do list to test the latest experimental release (20150126) and see if the problem is resolved in that branch.

https://github.com/libyal/libewf/releases

**Comment by theraven82** [comment] 2015-03-18 18:08
The problems seem indeed to start with 2TB images and larger (never noticed any problems with smaller size images). 
Tomorrow I'll test the experimental release (I downloaded libewf from googledrive, as linked [here](https://github.com/libyal/libewf/wiki/Building) ). I don't think it's a memory issue in my case, as it happens on systems with 4 GB memory and 8GB memory, at the same point.
I'll report back with the results.

**Comment by gregfreemyer** [comment] 2015-03-18 18:38
A 32 bit address pointer can only address 4GiB of memory (ram + virtual).  

(do the math, hex 0xFFFFFFFF is roughly 4 GB, and that is as big as you can go with 32 bits).

Thus a 32-bit linux app can only use 4GiB of the total memory per instance.  So even if you install that 32-bit executable on a 64-bit linux install with a TB of RAM, the app will only use 4GiB of it for its own internal use.

Thus your 2 systems effectively are the same from the perspective of ewfverify 32-bit.

A 64-bit app has a much larger address pointer to work with, so it can allocate and manage far greater amounts of ram.  (I'd have to google to get the limit, but it is truly huge.)

**Comment by theraven82** [comment] 2015-03-18 18:42
(Yeah, I understand.. I was a bit distracted posting the previous message). 

I'll go and sit quietly in a corner now ;)

I'll update tomorrow

**Comment by joachimmetz** [comment] 2015-03-18 20:28
I'll have a look when time permits.

**Comment by theraven82** [comment] 2015-03-19 11:14
Have compiled the latest experimental version (20150126), and so far so good. It's at 1.1 TB now, so no need to rush just yet.

**Closed** 2015-03-20 10:40 UTC
Labels: bug
