### ISSUE TITLE
ewfmount is mounting e01 in read-only mode

### ISSUE THREAD

**Issue by normaliok** [libyal/libewf#122] opened 2019-03-24 09:56 UTC
I have the same issue as here https://github.com/libyal/libewf/issues/113
-X allow_root doesn't help

**Comment by joachimmetz** [comment] 2019-03-24 13:46
That is as designed, ewfmount does not support write mode.

**Comment by normaliok** [comment] 2019-03-24 15:11
> That is as designed, ewfmount does not support write mode.

It's very pity (((

**Comment by joachimmetz** [comment] 2019-03-24 15:18
> It's very pity (((

No its not, it's deliberate. Forensics tools should limit write access as much as possible to prevent issues due to careless usage. If you cannot mount due to a dirty file system, there are work-arounds for this. However you'll need to be more specific in your issue report for me to be able to help you.

**Comment by normaliok** [comment] 2019-03-24 16:45
You might be wondered but on the interview for a forensics investigator position one of the questions was "how to boot up an image acquired from investigated machine?" So, it's needful option to have a read-write access to the image.

**Comment by joachimmetz** [comment] 2019-03-24 16:52
> You might be wondered but on the interview for a forensics investigator position one of the questions was "how to boot up an image acquired from investigated machine?" So, it's needful option to have a read-write access to the image.

A lot of virtualization software supports differential images that track change. So you can explain later on what has changed. Why does this require the ability to modify the original image?

**Comment by normaliok** [comment] 2019-03-24 17:16
Ah, forget it )) You may close this issue

**Comment by joachimmetz** [comment] 2019-03-24 18:47
@normaliok if you are unable to explain your issue or clarify point of view why adding this feature is necessary I'm unable to address it. I'll close the issue per your request.

**Closed by joachimmetz** 2019-03-24 18:47 UTC
Labels: question
