### ISSUE TITLE
ewfverify fails with largers images: libewf_chunk_data_initialize: invalid chunk data

### ISSUE THREAD

**Issue by retoo** [libyal/libewf#109] opened 2018-09-21 12:14 UTC
ewfverify version 20140804 and 20140608 both seem to have troubles verifying larger images. (Usually when the source device is larger than 1 TB).

See the following error 

```
Verify failed at: Sep 21, 2018 12:59:49
Status: at 49%.
        verified 917 GiB (984935530496 bytes) of total 1.8 TiB (2000398934016 bytes).
        completion in 1 hour(s), 4 minute(s) and 38 second(s) with 250 MiB/s (263071927 bytes/second).

Unable to verify input.
libewf_chunk_data_initialize: invalid chunk data.
libewf_read_io_handle_read_chunk_data: unable to create chunk data.
libewf_handle_read_buffer: unable to read chunk data: 30068951.
verification_handle_read_buffer: unable to read storage media buffer.
verification_handle_verify_input: unable to read data.
Killed
```

Please note 

The ewfverify bundeled with the paladin distribution (20160424) seems to be able to verify these images, but I wasn't able to find a source code release for 20160424.

**Comment by joachimmetz** [comment] 2018-09-21 22:08
Issue 1 paladin dist should reference the source otherwise they are violating the lgpl. Issue 2 anything beyond a 2014xxxx release is experimental.

I'll try to make the current experimental libewf stable when time permits.

**Comment by retoo** [comment] 2018-09-22 03:42
Please note : This error happens with the latest 2014 release I'm aware of.

**Comment by joachimmetz** [comment] 2018-09-22 03:59
I understand but 1 TB drives were not that common in 2014 and the EWF format has changed since 2014.

The most time effective is making the current experimental libewf stable when time permits.

**Comment by joachimmetz** [comment] 2018-09-22 04:01
This looks like a duplicate of https://github.com/libyal/libewf/issues/18

**Closed** 2019-12-24 15:57 UTC
Labels: duplicate
