### ISSUE TITLE
E01 files corrupt for large drives

### ISSUE THREAD

**Issue by PassMark** [libyal/libewf#104] opened 2018-08-08 04:44 UTC
When creating E01 files we discovered some of the E01 files are corrupt. 

After a bunch of experimentation we found it happened when the number of output files (segments) was > 64 files.

In particular the “Volume” section in the header of the first E01 file is corrupt. These two values, number_of_chunks[4 bytes], numbers_of_sectors[4 bytes] are wrong. They are zero but shouldn’t be.

<img width="550" alt="volumehex" src="https://user-images.githubusercontent.com/8924533/43816335-70cac1fc-9b17-11e8-856b-ffd96d18c2d0.png">

We had a bit of a look in the code. The following is our understanding of what happens. (Might not be exactly correct, as we didn't spend days looking at it).

When creating E01 files, the small header at the start of each split file isn’t written out to disk. The headers are all written at the end. (we didn't see any good reason for doing it this way, but that’s the way it is it seems). The data for the file headers is held in a memory buffer. Its described in the code as a cache. The cache was 128 records in size, but got reduced to 64 via a change in 2014 (there seems to be no good reasons for this change that I could find). In theory after the 64th file there is no more room in the cache for the header of the 65th file. At this point the oldest cache record should be evicted and written to disk to make space for the new one. In practice this doesn’t work, the write to disk doesn’t occur, and the contents of the old cache entry are lost due to some bug we never found. But this creates the corrupted file headers (with zero values) that we saw some of the time. We started to re-code the whole caching mechanism, but instead we went with the alternative fix of just making the cache much bigger. Enlarging it from 64 records to 5500 records, which is enough cache to image a 8TB drive (at 1.5GB per E01 split file). Using 5500 records will use slightly more RAM, but modern machines have ample available.

So the quick and dirty fix it is just to change LIBEWF_MAXIMUM_CACHE_ENTRIES_SEGMENT_FILES from 64 to a very large number (5500 in our case).

The clean fix would be to fix the cache eviction code, **or** just remove the entire concept of cache eviction (i.e. grow the buffers as required to hold all the data) **or** write out the header data on the fly and remove the cache entirely.

Likely it is the [same as the corruption problem identified in 2015](https://github.com/libyal/libewf/issues/22).

Hope this helps someone.
Regards
David

**Comment by joachimmetz** [comment] 2018-08-08 05:54
Which version of libewf are you using the experimental or last stable (legacy)?

**Comment by PassMark** [comment] 2018-08-08 21:38
We tried versions 20171104 and 20160424. Both have the problem.

We also suspect it impacts the creation of Ex01 files, also leaving them corrupt, even when the output file  is one large file (and isn't segmented into multiple files). But we are still testing the Ex01 behaviour so don't want to categorically claim it is the same issue yet.

**Comment by joachimmetz** [comment] 2018-08-09 05:39
> We tried versions 20171104 and 20160424. 

both are experimental.

**Comment by PassMark** [comment] 2018-08-10 01:02
Understood.

With this 1 line fix in place all the nominal testing we did passed. So it seems fairly solid otherwise.

**Comment by joachimmetz** [comment] 2018-08-10 06:48
Ack thx for that context, I'll get back to library as soon as time permits. Currently working on its dependencies

**Comment by JustMyGithub** [comment] 2020-10-26 06:59
I am not sure whether this is the same issue:

I created an e01 using ewfacquirestream 20200927 (cygwin) and the resulting e01 is rejected or warned about by several tools because it is for example "larger than expected". 

ewfinfo states its size was 0, nevertheless ewfrecover says that the image is fine.

> Media information:
>         Media type:             fixed disk
>         Is physical:            yes
>         Bytes per sector:       512
>         Number of sectors:      0
>         Media size:             0 B (0 bytes)

**Comment by joachimmetz** [comment] 2020-11-29 13:23
@JustMyGithub as indicated in https://github.com/libyal/libewf/issues/104#issuecomment-411642834, libewf version 20200927 is experimental use the legacy version (https://github.com/libyal/libewf-legacy) instead

**Comment by joachimmetz** [comment] 2020-11-29 13:28
> With this 1 line fix in place all the nominal testing we did passed (in a Windows environment). So it seems fairly solid otherwise.

@PassMark as you indicated yourself this 1 line "fix" is a "quick and dirty fix", changing the limit will not address the underlying issue.

I'll have a look if the issue persist with the current version of the experimental version.

**Comment by joachimmetz** [comment] 2020-11-29 14:02
Created an EWF image set with 207 segment files with https://github.com/libyal/libewf/commit/277e9ec047ee38eb6bbfe3f5bb067f4c4895c249.

EWF image set correctly verified and read by Encase, FTK imager and libewf-legacy. 

Unable to reproduce issue with current versions, closing

**Closed by joachimmetz** 2020-11-29 14:02 UTC
Labels: needs a closer look

**Comment by PassMark** [comment] 2020-12-29 04:36
We were still able to reproduce the problem with libewf-20201210. Creating a E01 with more than 64 parts fails.
Not sure if we are doing something wrong (or just different from your test cases). But we think the bug still exists.
Changing LIBEWF_MAXIMUM_CACHE_ENTRIES_SEGMENT_FILES to 5000 still fixes the problem however. So there is a trivial work-around.

**Comment by joachimmetz** [comment] 2020-12-29 05:36
@PassMark can you provide more details to help isolate the problem instead of urging to push your "fix". Since it only likely pushes the issue to happen at 5000 segment files.

> We were still able to reproduce the problem with libewf-20201210.

can you provide more information about:
* your build environment (compiler, version)
* your runtime environment (version)
* parameters passed

**Comment by PassMark** [comment] 2020-12-30 00:10
Test setup was as follows.

**Build environment:**
Compiler: Microsoft Visual C++ 2019
Windows SDK Version: 10.0.19041.0
Platform Toolset: Visual Studio 2019 (v142)
 
**Runtime environment:** 
OS: Microsoft Windows 10 Pro
Version: 10.0.19041 Build 19041
 
**EWF settings used:** 
Image format: LIBEWF_FORMAT_ENCASE6
Compression method: LIBEWF_COMPRESSION_METHOD_NONE
Segment size: 150MB
Source disk size: 16.94GB Partition (116 segments output)
